[package]
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
name = "cumulus-token-dealer"
version = "0.1.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

frame-support = { git = "https://github.com/cheme/substrate", default-features = false, branch = "rococo-branch-witness_backend" }
frame-system = { git = "https://github.com/cheme/substrate", default-features = false, branch = "rococo-branch-witness_backend" }

# Cumulus dependencies
cumulus-upward-message = { path = "../../../upward-message", default-features = false }
cumulus-primitives = { path = "../../../primitives", default-features = false }

# Polkadot dependencies
polkadot-parachain = { git = "https://github.com/cheme/polkadot-1", branch = "rococo-branch-witness_backend", default-features = false }

[features]
default = ["std"]
std = [
    "codec/std",
    "cumulus-upward-message/std",
    "cumulus-primitives/std",
    "frame-support/std",
    "frame-system/std",
    "polkadot-parachain/std",
]
